CREATE DATABASE UserLists;
USE UserLists;


CREATE TABLE Users(
Username VARCHAR(50) NOT NULL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Phone VARCHAR(15) NOT NULL,
Location VARCHAR(50) NOT NULL,
RegistrationDATE DATE NOT NULL,
Organization VARCHAR(15) NOT NULL,
Role VARCHAR(50) NOT NULL
);
